### PR TITLE
Fix regex for less

### PR DESCRIPTION
**Pull request by sitch**

### CODE REVIEW

**Comment by SolidZORO** [comment]
Did this solve any problems?

**Comment by sitch** [comment]
Yes this fixes an issue with building in serverless mode on next.js.  Could also just change the regex to be configurable via some setting for better compatibility

**Comment by austinwalter** [comment]
I can confirm that this fix allowed me to successfully build the project in serverless mode. I was unable to before.

**Comment by tgmarinho** [comment]
How can I test it in my project? I facing the same issue on Netlify.

**Comment by tgmarinho** [comment]
add to package.json to test it.

```
"next-plugin-antd-less": "SolidZORO/next-plugin-antd-less#57/head",

```

**Comment by tgmarinho** [comment]
I tested it in my project and it works! It should go to production ASAP ;)

Thanks for helping @sitch 🚀 

Solution for now: 
https://twitter.com/tgmarinho/status/1400213108019314691

**Comment by SolidZORO** [comment]
@sitch Sorry I'm late testing, just merged and released the new version.

**Pull request merged**
